### ISSUE TITLE
Error when building on rust 1.55.0

### ISSUE THREAD

**Issue by Madabaru** [regexident/rust-seal#1]
Hi,

I really like your crate and the fact that it allows alignment of sequences of strings.
I am afraid I run into the following error when trying to build on (the latest) rust version 1.55.0:

```
$ cargo build
   Compiling seal v0.1.0
error[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
  --> /home/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/seal-0.1.0/src/pair/alignment_matrix.rs:79:26
   |
79 |         self.mut_slice()[self.offset(cursor)] = byte;
   |         -----------------^^^^----------------
   |         |                |
   |         |                immutable borrow occurs here
   |         mutable borrow occurs here
   |         mutable borrow later used here
```
Appreciate any help!

**Comment by Madabaru** [comment]
Fortunately, I was able to fix the issue by adding the following line(s):
`  let offset = self.offset(cursor); 
   self.mut_slice()[offset] = byte;`

**Comment by Madabaru** [comment]
I fixed my issue by editing **"alignment_matrix.rs"** (lacated at _'/home/myusername/.cargo/registry/src/github.com-1ecc6299db9ec823/seal-0.1.0/src/pair/'_) on my local machine:

  ```
77      pub fn set_at(&mut self, cursor: &Cursor, step_mask: StepMask) {
78          let byte = unsafe { mem::transmute::<StepMask, u8>(step_mask) };
79          let offset = self.offset(cursor);
80          self.mut_slice()[offset] = byte;
  ```

**Comment by regexident** [comment]
Thanks for the report @Madabaru, could you try v0.1.1, which I just published?

**Comment by Madabaru** [comment]
Hi @regexident. Thank you very much! 

Unfortunately, the usage example seems to be outdated. I changed the required parameters in the function, but still encounter the following error: _type annotations needed for `Result<AlignmentSet<T>, E>`_ in the line below:

`  let set = AlignmentSet::new(seq_x.len(), seq_y.len(), strategy, |x, y| seq_x[x] == seq_y[y]);`

Could you maybe update the given usage example to your modifications  :) 
Appreciate  your work! :)

**Comment by regexident** [comment]
Thanks example should be fixed now, thanks for letting me know!

**Comment by Madabaru** [comment]
Thank you for your quick response! Works like a charm :)

**Comment by regexident** [comment]
I'm glad you found it useful!
